### ISSUE TITLE
Link broken in the README for `hipBLAS functions`

### ISSUE THREAD

**Issue by aurianer** [ROCmSoftwarePlatform/hipBLAS#454] opened 2022-02-01 19:21 UTC
The very last link of the README is broken.

**Comment by rkamd** [comment] 2022-02-01 20:48
@aurianer , Thanks for reporting, the issue is resolved in [PR#455](https://github.com/ROCmSoftwarePlatform/hipBLAS/pull/455)

**Closed by rkamd** 2022-02-01 20:48 UTC
